# SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: 'Dependabot auto approval'

on:
  pull_request_target

permissions:
  pull-requests: write
  contents:      write

jobs:
  dependabot:
    uses: xmidt-org/shared-go/.github/workflows/approve-dependabot.yml@f0ba95798ab73202b3f2812ea0209db07d99c6e8 # v4.5.4
    secrets: inherit
